SEED_PROMPTS = ["Eye Contact: Write about two people seeing each other for the first time.",
        "You are a childs imaginary friend. You are fading away as the child grows older. You have one last talk with the child the day before their 18th birthday.",
        "Arianna, a thing of cruelty and knowledge.",
        "In the early fall, that starship navigator was growing up.",
        "It will be the season of wisdom, the season of perversion.",
        "That lady, that person of complete justice.",
        "Then came the rogue AIs, but the truth isn't quite what some think.",
        "Oh cruelty . . . time to break.",
        "Break education as long as you are crying.",
        "This is a story that concerns education, getting old, and a drought - and it's a story worth repeating.",
        "Describe a wedding from three points of view.",
        "Prisoners won't try to excape if they don't even know they are in prison.",
        "You work as a memory soother for the United States military that erases the most horrific memories from traumatized soldiers coming home from war. One of your patients subconscious holds on to a certain memory sequence no matter how hard you try.",
        "Judgement day comes and all the worthy people are lifted into heaven above. Left on earth are the sinners and the disbelievers. ",
        "The man walked slowly towards the beast and the beast was afraid.",
        "Describe a wedding from three points of view.",
        "Describe a funeral from the dead persons perspective.",
        "She can see exactly how many days someone has to live.",
        "Humans are naturally emotionless. You can buy emotions from vendors to feel something for a little while.",
        "In the blistering hot summer, you and your friends go take a swim at the lake. You decide to have a competition to see who can dive the deepest. You dive in but when you come up for air you are engulfed in deep winter, with snow all around you. Your friends are gone.",
        "In some native american cultures, dreamcatchers are circular object on which is woven a loose net or web. The natives believe that a dreamcatcher changes a person's dreams. Only good dreams would be allowed to filter through... bad dreams would stay in the net. A dreamcatcher must be emptied of the nightmares it has caught. Who does it, and what do they see?",
        "Write a story involving a countdown. When it reaches 0 the story should end.",
        "Karma is a living entity that comes for everyone. If anyone ever gets sick, it's karma. If anyone gets in an accident, it's karma. If anyone experiences any misfortune, it's karma. Max is an 8 year-old and he just became an orphan.",
        "You come home late one night and jump into bed exhausted. You hear a vibration and clumsily grab your phone. It flashes you the text [ Why is your front door open?;( ]. Sent by unknown number.",
        "Write a story about three people who are on a road trip together, only to stop off at a gas station and pick up a fourth person whom they don't know. Why did they pick this person up? Where are they taking him/her? What happens?",
        "Write about finding a lost child. Something aboout this child seems off...",
        "They scrambled up the tree as quickly as they could. Yeah... That. Is. Not. A. Dog.",
        "You are a well known time-traveling therapist that assist many depressed people. They come to you with one request. Make sure they were never born.",
        " Write a scene that starts with a note at the holiday inn.",
        "You find a nifty old mask from a flea market. You wear it that evening to a halloween party. As the night goes on, you feel... a bit different.",
        "Write about an elaborate robbery",
        "Earth has two suns. As a result of the disrupting gravitatonal forces, earth's orbit is chaotic. Earth has years of extreme cold and years of extreme heat. All of life has adapted to the changing weather.",
        "Write an epic about an ordinary, modern day, man or woman, who goes through the 12 stages of the Hero's journey",
        "There is no day and night. There is only 99 years of sunlight and one year without. The 99 years are spent building, advancing technology and fortifiying. And unless this century is any different, it will also be rebuilding. Because when the darkness comes, so do they.",
        "An Indian legend says: When a human dies there is a bridge they must cross to enter into Heaven. At the head of the bridge waits every animal that human encountered during their lifetime. The animals, based on what they know of this person, decide which humans may cross the bridge ... and which are turned away.",
        "One day you come into work and find a cookie mysteriously placed on your desk. Grateful to whoever left this anonymous cookie, you eat it. The next morning you come in and find another cookie. This continues for months until one day a different object is left, and this time there's a note.",
        "Professional sports lifted the ban on enhancement drugs. 30 years later, the athletes are barely recognizable as human. Write in the perspective of a sports reporter for the world cup finals.",
        "Most water sources are now unconsumable by humans. The remaining reserves are quickly fortified and controlled.",
        "Write about a gladiator entering the ring for the first time.",
        "An incoming asteroid will colide with earth in 3 days. The news has been spread around the world. How would you spend the next three days despite the midst of chaos around you.",
        "And we realized at that moment, they were never dead. They were just asleep",
        "In old navajo legends, there is a creature called a skin-walkers that can take on the shape, image and appearence of another animal.",
        "You are mother nature herself, who raised humanity to the maturity that it is of now. Write how you feel about your child.",
        "There's an old myth in Ireland of a taxi or carriage. When you need it the most it will show up. It won't take you where you want to go, but to where you need to go.",
        "Describe depression as a living creature. What does it look like? How does it feed? Where does it live?",
        "Write about something ugly - war, fear, hate, or cruelty - but find the beauty(silver lining) in it or seomthing good that can come out of it.",
        "In old greek mythology, there is a legend of a group of dangerous creatures called the sirens, that lived near the rocky cliffs of cape Pelorem. The sirens would lure passing sailors with enchanting music and vocals, only to have them shipwreck off the sharp jagged rocks. Write about a modern day siren.",
        "The hidebehind is a old folklore creature that appears at the very corner of your vision. Sometimes a person takes a walk in the wilderness and sees something move at the corner of the eyes. When they turn around and see nothing, they may be followed by the hidebehind.",
        "Write about a world where aging always benefits the person. People will only get smarter, stronger, healthier, and bettter looking.",
        "Blood is thicker than water is a modern proverb to describe the importance of family over friends. The actual uncut phrase is -The blood of the covenant is stronger than the water of the womb. Write your story that exemplifies this new meaning.",
        "Write a letter to your younger self of half your current age. Encourage them to prepare for the dangers and hardships as well as the good fortune and happiness. Try not to change their life because you still want them to grow as a person into the you today.",
        "A group of boys, as a child, used to go to a secluded lake to swim, play, and just enjoy. As they all grew up, they all forgot about the lake. The day before graduation, they decide to come back one last time for old times sake. But after spending some time out in the waters, they notice something is very different.",
        "Describe the season fall/autumn in vivid detail. Make someone who doesnt care for the season to realize how wonderful it really is.",
        "She was a ____. He was a _____. Her father disaproved.",
        "What type of person is your alter ego? ",
        "A subtle virus has infected a majority of the population. It's symptom so subtle, no one really looked for it. It started off as a compulsion to efficiency. People were sprinting to coffee shops or reading textbooks for a small quiz. As a scientis, you start to take notice of these strange behavioiurs. 6 month's later, the next symptom starts to show.",
        "A global catastrphe has occured, cuttin off almost every electric grid. Write about the next few days as people realize they entering the new stone age.",
        "On the long flight to a foreign country, you wind up telling your seatmate much of your life story. Only it isn't yours. You've always wanted to pretend to be somebody else, just for an hour or two, and this seemed like the perfect oppurtunity."
        "You wake up one morning to a silent vibration from your phone. It read- Please remain in your homes, if you are not at home, find shelter immediately. Close all blinds and shades, block out all windows. Do not look outside. Do not look at the sky. Do not make noise. Your cooperation is vital to your survival. Appointed government personnel will update you shortly.",
        "You go to check the mail and see a package. That's great because you love packages. This one is wrapped in a dark red fabric that you've never really seen before... or felt before. The box begans to shake once you pick it up. That's when you realize you haven't even ordered anything.",
        "You are renting a room in someone's house as you transition to city life. The owner tells you the basement is absolutely one hundred percent off limits. As the weeks pass, you become obsessed with the basement. One day you manage to crack the lock and open the door. You slowly creak open the door, glance a peek inside, and immediately slam the door shut, putting all the locks back on. What did you see in there?",
        "You've been given one-time access to a time machine to visit your younger self. After a brief pause, you know the when and the where, hop in the machine and take off. When there, you chat with your younger self but offer one piece of advice to him/her that you hope will change his/her future for the better.",
        "After planning the most elaborate heist, you and your friends succesfully rob a bank of over 5 million dollars. Everyone celebrates that night but you are so tired that you go to your room to sleep. Lying there dreaming about your new future, you over hear your friends talking about killing you off."
        "You walk in a coffee shop and to your surpise there is a giant sword sticking out of the ceiling. For some reason, everyone at the shop is completely oblivious of the sword. What's going on ?",
        "You were involved in a terrible car accident and have been in a coma for the past three months. What your family and the doctors don't know is that you can hear everything that they say. Write the scene.",
        "You wake up and find out you are no longer in your room. You are in the middle of what seems to be a maze. On the wall is a note. It says [You have one hour to escape]. Write what happens next.",
        "You are just about leave to your car. Your friend stops you and says [ Becareful tonight, its the anniversary remember?]. You nod and walk outside.",
        "Start a scene between two people with, 'I honestly didn't think it was that bad of an idea'. End it with 'And that's why im facing 10-20 of federal prison'.",
        "You are helping out an old childhood friend with moving out. He/she is about move across the country and this might be the last time you see them. As you finish packing, they say they need to tell you a story about you. A story that you have never heard about and a story that will change your life.",
        "Write a letter to someone in your life that has passed away. You can tell that person the things you wish you'd said, tell that person some of the highlights of your life, whatever you want. If that's too difficult, have one of your characters from your novel (or short story) write a letter to a character he or she lost.",
        "You are looking for a job and come upon a strange posting in the newspaper. It reads -Team looking for full-time associate who isn't afraid of ghost-. With nothing to lose, you call them and get the job. On your first day, you get a call and go on your first assignment. Write about what happens.",
        " You get home and see a note posted on your door. It reads -I've taken your most prized possesion, meet me in person, alone, at midnight. Bring your baseball glove.- Strange note considering, you don't play baseball. Write about what happens next. "
        ]
